name: Rock Paper Scissors Game

on:
  issues:
    types:
      - opened
      - edited
      - deleted

jobs:
  play_game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run game script
        run: node .github/scripts/rps_game.js
